# Generated by Django 5.1.1 on 2024-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='priority_level',
            field=models.CharField(choices=[('Lo', 'Low'), ('Mid', 'Medium'), ('Hi', 'High')], default='Hi', max_length=10),
        ),
    ]
