# Generated by Django 5.1.1 on 2024-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
